// Generated mirror of the CSS custom-property contract.
export const TOKENS = {
  "--sn-white": "#ffffff",
  "--sn-paper": "#f5f5f5",
  "--sn-mist": "#eeeeee",
  "--sn-fog": "#e4e4e4",
  "--sn-linen": "#dedad4",
  "--sn-rule": "#d8d8d8",
  "--sn-border": "#e0e0e0",
  "--sn-silver": "#b3b3b3",
  "--sn-steel": "#8a8a8a",
  "--sn-slate": "#6e6e6e",
  "--sn-graphite": "#4d4d4d",
  "--sn-shadow-band": "#4f4f4f",
  "--sn-charcoal": "#2a2a2a",
  "--sn-ink": "#0a0a0a",
  "--sn-black": "#000000",
  "--surface-page": "var(--sn-white)",
  "--surface-alt": "var(--sn-paper)",
  "--surface-band": "var(--sn-mist)",
  "--surface-warm": "var(--sn-linen)",
  "--surface-invert": "var(--sn-black)",
  "--surface-invert-soft": "var(--sn-shadow-band)",
  "--surface-media": "var(--sn-fog)",
  "--text-display": "var(--sn-slate)",
  "--text-heading": "var(--sn-graphite)",
  "--text-body": "var(--sn-graphite)",
  "--text-muted": "var(--sn-steel)",
  "--text-faint": "var(--sn-silver)",
  "--text-strong": "var(--sn-ink)",
  "--text-on-invert": "var(--sn-white)",
  "--text-on-invert-muted": "rgba(255,255,255,.72)",
  "--text-link": "var(--sn-ink)",
  "--text-link-hover": "var(--sn-steel)",
  "--accent": "var(--sn-ink)",
  "--accent-contrast": "var(--sn-white)",
  "--accent-soft": "var(--sn-mist)",
  "--accent-line": "var(--sn-rule)",
  "--accent-2": "var(--sn-graphite)",
  "--state-positive": "#1f7a4d",
  "--state-warning": "#b07000",
  "--state-critical": "#b3261e",
  "--state-info": "#2a5d9f",
  "--state-positive-soft": "#e8f3ed",
  "--state-warning-soft": "#fbf1df",
  "--state-critical-soft": "#fbeae9",
  "--state-info-soft": "#e9f0f9",
  "--font-core": 'var(--sn-font-inter),"Helvetica Neue",Arial,sans-serif',
  "--font-display": 'var(--sn-font-cy-grotesk),"Helvetica Neue",Arial,sans-serif',
  "--font-editorial": 'var(--sn-font-inter),"Helvetica Neue",Arial,sans-serif',
  "--font-campaign": 'var(--sn-font-cy-grotesk),"Helvetica Neue",Arial,sans-serif',
  "--font-label": 'var(--sn-font-gotham),"Helvetica Neue",Arial,sans-serif',
  "--font-black": 'var(--sn-font-neue-haas),"Helvetica Neue",Arial,sans-serif',
  "--font-mono": "var(--sn-font-plex-mono),ui-monospace,SFMono-Regular,Menlo,monospace",
  "--font-brand-gothic": "var(--sn-font-cook-gothif),var(--font-display)",
  "--font-brand-script": "var(--sn-font-missing-lovely),cursive",
  "--fw-display-min": "500",
  "--fw-display": "800",
  "--fw-label": "400",
  "--fw-thin": "200",
  "--fw-light": "300",
  "--fw-regular": "400",
  "--fw-medium": "500",
  "--fw-semibold": "600",
  "--fw-bold": "700",
  "--fw-heavy": "800",
  "--fwd-condensed": "75",
  "--fwd-normal": "100",
  "--fs-display-1": "72px",
  "--fs-display-2": "56px",
  "--fs-display-3": "44px",
  "--lh-display": "1.06",
  "--tr-display": "0.02em",
  "--fs-h1": "36px",
  "--fs-h2": "30px",
  "--fs-h3": "24px",
  "--fs-h4": "20px",
  "--fs-h5": "17px",
  "--lh-heading": "1.22",
  "--tr-heading": "-0.005em",
  "--fs-lead": "20px",
  "--fs-body": "16px",
  "--fs-body-sm": "14px",
  "--fs-caption": "12px",
  "--lh-body": "1.62",
  "--lh-lead": "1.5",
  "--lh-tight": "1.35",
  "--fs-eyebrow": "12px",
  "--tr-eyebrow": "0.14em",
  "--fw-eyebrow": "600",
  "--fs-stat": "68px",
  "--fw-stat": "300",
  "--fs-campaign-1": "88px",
  "--fs-campaign-2": "60px",
  "--fs-xxxl": "212px",
  "--fs-xxl": "126px",
  "--fs-xl": "102px",
  "--tr-xxl": "-0.01em",
  "--fs-campaign-3": "40px",
  "--lh-campaign": "1.0",
  "--tr-campaign": "-0.01em",
  "--breakpoint-sm": "480px",
  "--breakpoint-md": "768px",
  "--breakpoint-lg": "1024px",
  "--breakpoint-xl": "1280px",
  "--breakpoint-2xl": "1440px",
  "--sp-1": "4px",
  "--sp-2": "8px",
  "--sp-3": "12px",
  "--sp-4": "16px",
  "--sp-5": "24px",
  "--sp-6": "32px",
  "--sp-7": "40px",
  "--sp-8": "48px",
  "--sp-9": "64px",
  "--sp-10": "80px",
  "--sp-11": "96px",
  "--sp-12": "128px",
  "--sp-13": "160px",
  "--sp-14": "200px",
  "--section-y": "clamp(56px,9vw,var(--sp-13))",
  "--section-y-tight": "clamp(48px,6vw,var(--sp-11))",
  "--stack-xs": "var(--sp-2)",
  "--stack-sm": "var(--sp-4)",
  "--stack-md": "var(--sp-6)",
  "--stack-lg": "var(--sp-9)",
  "--stack-xl": "var(--sp-12)",
  "--admin-gap": "var(--sp-4)",
  "--admin-pad": "var(--sp-5)",
  "--admin-row-y": "var(--sp-3)",
  "--page-max": "1440px",
  "--page-margin": "clamp(20px,5.3vw,76px)",
  "--content-max": "1288px",
  "--measure": "68ch",
  "--measure-tight": "46ch",
  "--grid-cols": "12",
  "--grid-gutter": "24px",
  "--media-ratio-wide": "16/9",
  "--media-ratio-editorial": "4/3",
  "--media-ratio-portrait": "3/4",
  "--media-ratio-square": "1/1",
  "--admin-sidebar": "248px",
  "--admin-topbar": "56px",
  "--admin-max": "1600px",
  "--z-nav": "100",
  "--z-overlay": "200",
  "--z-modal": "300",
  "--radius-none": "0px",
  "--radius-xs": "2px",
  "--radius-sm": "4px",
  "--radius-pill": "999px",
  "--radius-circle": "50%",
  "--border-width": "1px",
  "--border-hairline": "1px solid var(--sn-border)",
  "--border-rule": "1px solid var(--sn-rule)",
  "--border-strong": "1px solid var(--sn-ink)",
  "--border-on-invert": "1px solid rgba(255,255,255,.28)",
  "--rule-short-w": "200px",
  "--shadow-none": "none",
  "--shadow-admin": "0 1px 2px rgba(10,10,10,.06)",
  "--shadow-admin-raised": "0 4px 16px rgba(10,10,10,.10)",
  "--focus-ring": "2px solid var(--sn-ink)",
  "--focus-offset": "2px",
  "--dur-instant": "120ms",
  "--dur-fast": "200ms",
  "--dur-base": "320ms",
  "--dur-slow": "640ms",
  "--dur-reveal": "900ms",
  "--ease-standard": "cubic-bezier(.22,.61,.36,1)",
  "--ease-out": "cubic-bezier(.16,1,.3,1)",
  "--ease-in-out": "cubic-bezier(.65,0,.35,1)",
  "--dur-stagger": "90ms",
  "--reveal-shift": "24px",
  "--reveal-shift-lines": "105%",
  "--media-zoom": "1.03",
  "--hover-fade": ".62",
  "--press-fade": ".45"
} as const;

export type TokenName = keyof typeof TOKENS;
